web/router.ex
defmodule PortfolioPhoenix.Router do
  use PortfolioPhoenix.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.EnsureAuthenticated,
      handler: PortfolioPhoenix.SessionController
  end

  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug PortfolioPhoenix.CurrentUser
  end

  scope "/", PortfolioPhoenix do
    pipe_through [:browser, :browser_auth]

    get "/", PageController, :index
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/posts", PostController
  end

  scope "/api", PortfolioPhoenix do
    pipe_through :api

    post "/image/upload", PostController, :create_photo
    delete "/image/remove", PostController, :remove_file
  end
end

web/views/layout_view.ex
defmodule PortfolioPhoenix.LayoutView do
  use PortfolioPhoenix.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>I'm Denver</title>
    <link href="https://fonts.googleapis.com/css?family=Gentium+Book+Basic:400,700" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/ocean.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav">
            <li>
              <i class="fa fa-code" aria-hidden="true"></i> Denver Smith
            </li>
            <%= if @current_user do %>
              <li>
                <%= link "Sign out", to: session_path(@conn, :delete, @current_user), method: "delete" %>
              </li>
            <%= end %>
            <li class="hideifsmall">|</li>
            <li><%= link "About", to: page_path(@conn, :index) %></li>
            <li><%= link "Posts", to: post_path(@conn, :index) %></li>
          </ul>
        </nav>
      </header>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <footer class="footer">
      <p>🍕  🚲  ❤️ </br>© 2017 Denver Smith</p>
    </footer>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>